FROM rocker/shiny-verse:latest

## Install any Linux system dependencies
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev 


# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

## Install R libraries
RUN R -e "install.packages('shiny',dependencies = TRUE)"
RUN R -e "install.packages('shinythemes',dependencies = TRUE)"
RUN R -e "install.packages('shinydashboard',dependencies = TRUE)"
RUN R -e "install.packages('DT',dependencies = TRUE)"
RUN R -e "install.packages('dplyr',dependencies = TRUE)"
RUN R -e "install.packages('visdat',dependencies = TRUE)"
RUN R -e "install.packages('ggplot2',dependencies = TRUE)"
RUN R -e "install.packages('shinycssloaders',dependencies = TRUE)"
RUN R -e "install.packages('vcd',dependencies = TRUE)"
RUN R -e "install.packages('car',dependencies = TRUE)"
RUN R -e "install.packages('corrgram',dependencies = TRUE)"
RUN R -e "install.packages('RColorBrewer',dependencies = TRUE)"
RUN R -e "install.packages('GGally',dependencies = TRUE)"
RUN R -e "install.packages('Hmisc',dependencies = TRUE)"
RUN R -e "install.packages('tidyr',dependencies = TRUE)"
RUN R -e "install.packages('dlookr',dependencies = TRUE)"
RUN R -e "install.packages('forecast',dependencies = TRUE)"
RUN R -e "install.packages('foreach',dependencies = TRUE)"
RUN R -e "install.packages('extrafont',dependencies = TRUE)"
RUN R -e "install.packages('partykit',dependencies = TRUE)"
RUN R -e "install.packages('quadprog',dependencies = TRUE)"
RUN R -e "install.packages('seriation',dependencies = TRUE)"


## Copy Shiny application files
COPY /App /srv/shiny-server/

## Grant access to server directory
RUN sudo chown -R shiny:shiny /srv/shiny-server

## Open the port for Shiny
EXPOSE 3838

## Start Shiny Server
CMD ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]